home@U2401:~/p/g/n/dspex$ mix dialyzer
Compiling 13 files (.ex)
Generated dspex app
Finding suitable PLTs
Checking PLT...
[:compiler, :dspex, :elixir, :ex_unit, :jason, :kernel, :logger, :mix, :nimble_pool, :stdlib, :telemetry, :telemetry_poller]
PLT is up to date!
ignore_warnings: .dialyzer_ignore.exs

Starting Dialyzer
[
  check_plt: false,
  init_plt: ~c"/home/home/p/g/n/dspex/priv/plts/dialyzer.plt",
  files: [~c"/home/home/p/g/n/dspex/_build/dev/lib/dspex/ebin/Elixir.DSPex.PythonBridge.PoolErrorHandler.beam",
   ~c"/home/home/p/g/n/dspex/_build/dev/lib/dspex/ebin/Elixir.DSPex.Adapters.Adapter.beam",
   ~c"/home/home/p/g/n/dspex/_build/dev/lib/dspex/ebin/Elixir.DSPex.PythonBridge.ErrorReporter.beam",
   ~c"/home/home/p/g/n/dspex/_build/dev/lib/dspex/ebin/Elixir.DSPex.Signature.beam",
   ~c"/home/home/p/g/n/dspex/_build/dev/lib/dspex/ebin/Elixir.DSPex.Signature.JsonSchema.beam",
   ...],
  warnings: [:error_handling, :extra_return, :missing_return, :underspecs, ...]
]
Total errors: 72, Skipped: 3, Unnecessary Skips: 0
done in 0m1.72s
lib/dspex.ex:163:9:unmatched_return
The expression produces a value of type:

:ok | {:error, binary()}

but this value is unmatched.

________________________________________________________________________________
lib/dspex/adapters/python_pool_v2.ex:406:8:pattern_match
The pattern can never match the type.

Pattern:
{:pool_timeout, _reason}

Type:
%{:context => map(), :pool_error => true, _ => _}

________________________________________________________________________________
lib/dspex/adapters/python_pool_v2.ex:410:8:pattern_match
The pattern can never match the type.

Pattern:
{:checkout_failed, _reason}

Type:
%{:context => map(), :pool_error => true, _ => _}

________________________________________________________________________________
lib/dspex/adapters/python_pool_v2.ex:414:8:pattern_match
The pattern can never match the type.

Pattern:
{:decode_error, _reason}

Type:
%{:context => map(), :pool_error => true, _ => _}

________________________________________________________________________________
lib/dspex/adapters/python_pool_v2.ex:418:8:pattern_match
The pattern can never match the type.

Pattern:
:response_mismatch

Type:
%{:context => map(), :pool_error => true, _ => _}

________________________________________________________________________________
lib/dspex/adapters/python_pool_v2.ex:422:8:pattern_match
The pattern can never match the type.

Pattern:
:malformed_response

Type:
%{:context => map(), :pool_error => true, _ => _}

________________________________________________________________________________
lib/dspex/python_bridge/circuit_breaker.ex:405:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.CircuitBreaker.handle_failure/2

Type specification:
@spec handle_failure(circuit(), term()) :: circuit()

Success typing:
@spec handle_failure(
  %{
    :config => map(),
    :failure_count => non_neg_integer(),
    :half_open_count => non_neg_integer(),
    :last_failure => nil | integer(),
    :last_state_change => integer(),
    :name => atom(),
    :state => :closed | :half_open | :open,
    :success_count => non_neg_integer()
  },
  _
) :: %{
  :config => map(),
  :failure_count => pos_integer(),
  :half_open_count => non_neg_integer(),
  :last_failure => integer(),
  :last_state_change => integer(),
  :name => atom(),
  :state => :closed | :half_open | :open,
  :success_count => non_neg_integer()
}

________________________________________________________________________________
lib/dspex/python_bridge/circuit_breaker.ex:457:missing_range
The type specification is missing types returned by function.

Function:
DSPex.PythonBridge.CircuitBreaker.time_until_retry/1

Type specification return types:
non_neg_integer()

Missing from spec:
float()

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:287:unmatched_return
The expression produces a value of type:

nil | {:exit, _} | {:ok, _}

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:335:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorRecoveryOrchestrator.load_recovery_strategies/1

Type specification:
@spec load_recovery_strategies(:elixir.keyword()) :: map()

Success typing:
@spec load_recovery_strategies(Keyword.t()) :: %{
  :communication_error => _,
  :connection_error => _,
  :health_check_error => _,
  :initialization_error => _,
  :python_error => _,
  :resource_error => _,
  :session_error => _,
  :system_error => _,
  :timeout_error => _,
  _ => _
}

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:468:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorRecoveryOrchestrator.execute_retry_recovery/2

Type specification:
@spec execute_retry_recovery(map(), recovery_strategy()) :: {:ok, term()} | {:error, term()}

Success typing:
@spec execute_retry_recovery(
  %DSPex.PythonBridge.PoolErrorHandler{
    :context => map(),
    :error_category =>
      :communication_error
      | :connection_error
      | :health_check_error
      | :initialization_error
      | :python_error
      | :resource_error
      | :session_error
      | :system_error
      | :timeout_error,
    :message => binary(),
    :pool_error => true,
    :recoverable => boolean(),
    :recovery_strategy =>
      :abandon | :backoff_retry | :circuit_break | :failover | :immediate_retry,
    :retry_after => nil | 100 | 500 | 1000 | 5000 | 10000,
    :severity => :critical | :major | :minor | :warning,
    :test_layer => :layer_1 | :layer_2 | :layer_3,
    :type =>
      :bridge_error
      | :connection_failed
      | :program_not_found
      | :timeout
      | :unexpected
      | :unknown
      | :validation_failed
  },
  %{
    :backoff => atom(),
    :circuit_breaker => nil | :pool_connections | :pool_resources | :worker_initialization,
    :custom_function => nil | (... -> any),
    :fallback_adapter => DSPex.Adapters.Mock | DSPex.Adapters.PythonPort,
    :max_attempts => pos_integer(),
    :max_recovery_time => 2500 | 5000 | 10000 | 15000 | 30000 | 60000,
    :type => :abandon | :circuit_break | :custom | :failover | :retry_with_backoff
  }
) ::
  {:error, :no_original_operation | %{:context => map(), :pool_error => true, _ => _}}
  | {:ok, _}

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:470:guard_fail
The guard clause:

when _ :: map() === nil

can never succeed.

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:487:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorRecoveryOrchestrator.execute_failover_recovery/2

Type specification:
@spec execute_failover_recovery(map(), recovery_strategy()) :: {:ok, term()} | {:error, term()}

Success typing:
@spec execute_failover_recovery(
  %DSPex.PythonBridge.PoolErrorHandler{
    :context => map(),
    :error_category =>
      :communication_error
      | :connection_error
      | :health_check_error
      | :initialization_error
      | :python_error
      | :resource_error
      | :session_error
      | :system_error
      | :timeout_error,
    :message => binary(),
    :pool_error => true,
    :recoverable => boolean(),
    :recovery_strategy =>
      :abandon | :backoff_retry | :circuit_break | :failover | :immediate_retry,
    :retry_after => nil | 100 | 500 | 1000 | 5000 | 10000,
    :severity => :critical | :major | :minor | :warning,
    :test_layer => :layer_1 | :layer_2 | :layer_3,
    :type =>
      :bridge_error
      | :connection_failed
      | :program_not_found
      | :timeout
      | :unexpected
      | :unknown
      | :validation_failed
  },
  %{
    :backoff => atom(),
    :circuit_breaker => nil | :pool_connections | :pool_resources | :worker_initialization,
    :custom_function => nil | (... -> any),
    :fallback_adapter => DSPex.Adapters.Mock | DSPex.Adapters.PythonPort,
    :max_attempts => pos_integer(),
    :max_recovery_time => 2500 | 5000 | 10000 | 15000 | 30000 | 60000,
    :type => :abandon | :circuit_break | :custom | :failover | :retry_with_backoff
  }
) ::
  {:error,
   {:failover_failed,
    %DSPex.Adapters.ErrorHandler{
      :context => map(),
      :message => binary(),
      :recoverable => boolean(),
      :retry_after => nil | 100 | 500 | 1000 | 5000 | 10000,
      :test_layer => :layer_1 | :layer_2 | :layer_3,
      :type =>
        :bridge_error
        | :connection_failed
        | :program_not_found
        | :timeout
        | :unexpected
        | :unknown
        | :validation_failed
    }}}
  | {:ok, {:failover, _}}

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:494:guard_fail
The guard clause:

when _ :: map() === nil

can never succeed.

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:573:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorRecoveryOrchestrator.get_circuit_breaker_name/1

Type specification:
@spec get_circuit_breaker_name(map()) :: atom() | nil

Success typing:
@spec get_circuit_breaker_name(%DSPex.PythonBridge.PoolErrorHandler{
  :context => map(),
  :error_category =>
    :communication_error
    | :connection_error
    | :health_check_error
    | :initialization_error
    | :python_error
    | :resource_error
    | :session_error
    | :system_error
    | :timeout_error,
  :message => binary(),
  :pool_error => true,
  :recoverable => boolean(),
  :recovery_strategy =>
    :abandon | :backoff_retry | :circuit_break | :failover | :immediate_retry,
  :retry_after => nil | 100 | 500 | 1000 | 5000 | 10000,
  :severity => :critical | :major | :minor | :warning,
  :test_layer => :layer_1 | :layer_2 | :layer_3,
  :type =>
    :bridge_error
    | :connection_failed
    | :program_not_found
    | :timeout
    | :unexpected
    | :unknown
    | :validation_failed
}) :: nil | :pool_connections | :pool_resources | :worker_initialization

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:583:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorRecoveryOrchestrator.get_fallback_adapter/1

Type specification:
@spec get_fallback_adapter(map()) :: module() | nil

Success typing:
@spec get_fallback_adapter(%DSPex.PythonBridge.PoolErrorHandler{
  :context => map(),
  :error_category =>
    :communication_error
    | :connection_error
    | :health_check_error
    | :initialization_error
    | :python_error
    | :resource_error
    | :session_error
    | :system_error
    | :timeout_error,
  :message => binary(),
  :pool_error => true,
  :recoverable => boolean(),
  :recovery_strategy =>
    :abandon | :backoff_retry | :circuit_break | :failover | :immediate_retry,
  :retry_after => nil | 100 | 500 | 1000 | 5000 | 10000,
  :severity => :critical | :major | :minor | :warning,
  :test_layer => :layer_1 | :layer_2 | :layer_3,
  :type =>
    :bridge_error
    | :connection_failed
    | :program_not_found
    | :timeout
    | :unexpected
    | :unknown
    | :validation_failed
}) :: DSPex.Adapters.Mock | DSPex.Adapters.PythonPort

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:585:guard_fail
The guard clause:

when _ :: map() === nil

can never succeed.

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:592:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorRecoveryOrchestrator.calculate_max_recovery_time/1

Type specification:
@spec calculate_max_recovery_time(map()) :: pos_integer()

Success typing:
@spec calculate_max_recovery_time(%DSPex.PythonBridge.PoolErrorHandler{
  :context => map(),
  :error_category =>
    :communication_error
    | :connection_error
    | :health_check_error
    | :initialization_error
    | :python_error
    | :resource_error
    | :session_error
    | :system_error
    | :timeout_error,
  :message => binary(),
  :pool_error => true,
  :recoverable => boolean(),
  :recovery_strategy =>
    :abandon | :backoff_retry | :circuit_break | :failover | :immediate_retry,
  :retry_after => nil | 100 | 500 | 1000 | 5000 | 10000,
  :severity => :critical | :major | :minor | :warning,
  :test_layer => :layer_1 | :layer_2 | :layer_3,
  :type =>
    :bridge_error
    | :connection_failed
    | :program_not_found
    | :timeout
    | :unexpected
    | :unknown
    | :validation_failed
}) :: 2500 | 5000 | 10000 | 15000 | 30000 | 60000

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:603:guard_fail
The guard clause:

when _ :: map() === nil

can never succeed.

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:607:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorRecoveryOrchestrator.update_success_metrics/2

Type specification:
@spec update_success_metrics(map(), integer()) :: map()

Success typing:
@spec update_success_metrics(map(), integer()) :: %{
  :avg_recovery_time => integer(),
  :total_recovery_time => integer(),
  _ => _
}

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:633:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorRecoveryOrchestrator.emit_telemetry/3

Type specification:
@spec emit_telemetry(atom(), map(), map()) :: :ok

Success typing:
@spec emit_telemetry(:recovery_complete, %{:duration => integer()}, %{
  :error_category => _,
  :recovery_id => binary(),
  :result => _,
  :strategy => :abandon | :circuit_break | :custom | :failover | :retry_with_backoff
}) :: :ok

________________________________________________________________________________
lib/dspex/python_bridge/error_recovery_orchestrator.ex:490:11:pattern_match
The pattern can never match the type.

Pattern:
nil

Type:
DSPex.Adapters.Mock | DSPex.Adapters.PythonPort

________________________________________________________________________________
lib/dspex/python_bridge/error_reporter.ex:272:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorReporter.build_config/1

Type specification:
@spec build_config(:elixir.keyword()) :: map()

Success typing:
@spec build_config(Keyword.t()) :: %{
  :alert_cooldown_ms => _,
  :alert_destinations => _,
  :alert_window_ms => _,
  :circuit_open_threshold => _,
  :cleanup_interval => _,
  :error_rate_threshold => _,
  :max_window_events => _,
  :min_events_for_alert => _,
  :monitoring_enabled => _,
  _ => _
}

________________________________________________________________________________
lib/dspex/python_bridge/error_reporter.ex:464:unmatched_return
The expression produces a value of type:


  nil
  | %DSPex.PythonBridge.ErrorReporter{
      :alert_history => :queue.queue(_),
      :circuit_states => _,
      :config => _,
      :error_counts => _,
      :event_window => :queue.queue(_),
      :last_cleanup => _
    }


but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/error_reporter.ex:495:unmatched_return
The expression produces a value of type:


  nil
  | %DSPex.PythonBridge.ErrorReporter{
      :alert_history => :queue.queue(_),
      :circuit_states => _,
      :config => _,
      :error_counts => _,
      :event_window => :queue.queue(_),
      :last_cleanup => _
    }


but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/error_reporter.ex:548:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorReporter.send_logger_alert/1

Type specification:
@spec send_logger_alert(map()) :: :ok

Success typing:
@spec send_logger_alert(%{
  :message => <<_::8, _::size(1)>>,
  :metadata => map(),
  :timestamp => integer(),
  :type => :circuit_opened | :high_error_rate | :multiple_circuits_open | :test_alert,
  :circuit => _,
  :error_count => non_neg_integer(),
  :error_rate => float(),
  :open_count => non_neg_integer(),
  :total_count => non_neg_integer()
}) :: :ok

________________________________________________________________________________
lib/dspex/python_bridge/error_reporter.ex:565:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorReporter.send_telemetry_alert/1

Type specification:
@spec send_telemetry_alert(map()) :: :ok

Success typing:
@spec send_telemetry_alert(%{
  :message => <<_::8, _::size(1)>>,
  :metadata => map(),
  :timestamp => integer(),
  :type => :circuit_opened | :high_error_rate | :multiple_circuits_open | :test_alert,
  :circuit => _,
  :error_count => non_neg_integer(),
  :error_rate => float(),
  :open_count => non_neg_integer(),
  :total_count => non_neg_integer()
}) :: :ok

________________________________________________________________________________
lib/dspex/python_bridge/error_reporter.ex:638:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.ErrorReporter.add_to_queue/3

Type specification:
@spec add_to_queue(:queue.queue(), term(), pos_integer()) :: :queue.queue()

Success typing:
@spec add_to_queue(
  :queue.queue(_),
  %{
    :message => <<_::8, _::size(1)>>,
    :metadata => map(),
    :timestamp => integer(),
    :type => :circuit_opened | :high_error_rate | :multiple_circuits_open,
    :circuit => _,
    :error_count => non_neg_integer(),
    :error_rate => float(),
    :open_count => non_neg_integer(),
    :total_count => non_neg_integer()
  },
  50
) :: :queue.queue(_)

________________________________________________________________________________
lib/dspex/python_bridge/error_reporter.ex:260:5:unmatched_return
The expression produces a value of type:

:ok | {:error, :not_found}

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/error_reporter.ex:294:5:unmatched_return
The expression produces a value of type:

:ok | {:error, :already_exists}

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/pool_error_handler.ex:89:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.PoolErrorHandler.wrap_pool_error/2

Type specification:
@spec wrap_pool_error(term(), map()) :: map()

Success typing:
@spec wrap_pool_error(_, map()) :: %DSPex.PythonBridge.PoolErrorHandler{
  :context => map(),
  :error_category =>
    :communication_error
    | :connection_error
    | :health_check_error
    | :initialization_error
    | :python_error
    | :resource_error
    | :session_error
    | :system_error
    | :timeout_error,
  :message => binary(),
  :pool_error => true,
  :recoverable => boolean(),
  :recovery_strategy =>
    :abandon | :backoff_retry | :circuit_break | :failover | :immediate_retry,
  :retry_after => nil | 100 | 500 | 1000 | 5000 | 10000,
  :severity => :critical | :major | :minor | :warning,
  :test_layer => :layer_1 | :layer_2 | :layer_3,
  :type =>
    :bridge_error
    | :connection_failed
    | :program_not_found
    | :timeout
    | :unexpected
    | :unknown
    | :validation_failed
}

________________________________________________________________________________
lib/dspex/python_bridge/pool_error_handler.ex:254:extra_range
The type specification has too many types for the function.

Function:
DSPex.PythonBridge.PoolErrorHandler.determine_base_severity/2

Extra type:
:warning

Success typing:
:critical | :major | :minor

________________________________________________________________________________
lib/dspex/python_bridge/pool_error_handler.ex:279:extra_range
The type specification has too many types for the function.

Function:
DSPex.PythonBridge.PoolErrorHandler.upgrade_severity/1

Extra type:
:minor | :warning

Success typing:
:critical | :major

________________________________________________________________________________
lib/dspex/python_bridge/pool_error_handler.ex:267:9:pattern_match_cov
The pattern
:variable_

can never match, because previous clauses completely cover the type

  :communication_error
  | :connection_error
  | :health_check_error
  | :initialization_error
  | :python_error
  | :resource_error
  | :session_error
  | :system_error
  | :timeout_error
.

________________________________________________________________________________
lib/dspex/python_bridge/pool_worker_v2.ex:288:guard_fail
The guard clause:

when _ :: true === nil

can never succeed.

________________________________________________________________________________
lib/dspex/python_bridge/pool_worker_v2.ex:210:33:pattern_match
The pattern can never match the type.

Pattern:
{:error, :port_not_owned}

Type:
{:error, :badarg | :not_a_port | :port_closed_during_connect | {:connect_failed, _}}

________________________________________________________________________________
lib/dspex/python_bridge/pool_worker_v2.ex:251:33:pattern_match
The pattern can never match the type.

Pattern:
{:error, :port_not_owned}

Type:
{:error, :badarg | :not_a_port | :port_closed_during_connect | {:connect_failed, _}}

________________________________________________________________________________
lib/dspex/python_bridge/pool_worker_v2_enhanced.ex:380:guard_fail
The guard clause:

when _ :: true === nil

can never succeed.

________________________________________________________________________________
lib/dspex/python_bridge/pool_worker_v2_enhanced.ex:488:guard_fail
The guard clause:

when _ :: true === nil

can never succeed.

________________________________________________________________________________
lib/dspex/python_bridge/retry_logic.ex:296:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.RetryLogic.should_retry?/2

Type specification:
@spec should_retry?(map(), pos_integer()) :: boolean()

Success typing:
@spec should_retry?(%{:context => map(), :pool_error => true, _ => _}, pos_integer()) :: boolean()

________________________________________________________________________________
lib/dspex/python_bridge/retry_logic.ex:324:missing_range
The type specification is missing types returned by function.

Function:
DSPex.PythonBridge.RetryLogic.calculate_decorrelated_jitter/3

Type specification return types:
non_neg_integer()

Missing from spec:
float()

________________________________________________________________________________
lib/dspex/python_bridge/session_affinity.ex:157:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.SessionAffinity.get_stats/0

Type specification:
@spec get_stats() :: map()

Success typing:
@spec get_stats() :: %{
  :expired_sessions => non_neg_integer(),
  :total_sessions => non_neg_integer(),
  :workers_with_sessions => non_neg_integer()
}

________________________________________________________________________________
lib/dspex/python_bridge/session_affinity.ex:190:14:unmatched_return
The expression produces a value of type:

atom() | :ets.tid()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool.ex:248:11:unmatched_return
The expression produces a value of type:

%{:metrics => map(), _ => _}

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool.ex:284:11:unmatched_return
The expression produces a value of type:

%{:metrics => map(), _ => _}

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool.ex:369:13:unmatched_return
The expression produces a value of type:

false | non_neg_integer()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool.ex:370:13:unmatched_return
The expression produces a value of type:

false | non_neg_integer()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool.ex:386:10:unmatched_return
The expression produces a value of type:

{:ok, pid()}

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool.ex:461:9:pattern_match_cov
The pattern
:variable_

can never match, because previous clauses completely cover the type
:pool_timeout.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:226:guard_fail
The guard clause:

when _ :: true === nil

can never succeed.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:289:missing_range
The type specification is missing types returned by function.

Function:
DSPex.PythonBridge.SessionPoolV2.handle_pool_error/2

Type specification return types:
{:error, _}

Missing from spec:
{:ok, _}

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:319:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.SessionPoolV2.handle_response_mismatch/3

Type specification:
@spec handle_response_mismatch(integer(), integer(), map()) :: map()

Success typing:
@spec handle_response_mismatch(non_neg_integer(), non_neg_integer(), %{
  :adapter => DSPex.PythonBridge.SessionPoolV2,
  :args => _,
  :command => _,
  :from => _,
  :operation => :execute_anonymous | :execute_command,
  :worker_id => _,
  :worker_state => atom(),
  :session_id => _
}) :: %DSPex.PythonBridge.PoolErrorHandler{
  :context => map(),
  :error_category =>
    :communication_error
    | :connection_error
    | :health_check_error
    | :initialization_error
    | :python_error
    | :resource_error
    | :session_error
    | :system_error
    | :timeout_error,
  :message => binary(),
  :pool_error => true,
  :recoverable => boolean(),
  :recovery_strategy =>
    :abandon | :backoff_retry | :circuit_break | :failover | :immediate_retry,
  :retry_after => nil | 100 | 500 | 1000 | 5000 | 10000,
  :severity => :critical | :major | :minor | :warning,
  :test_layer => :layer_1 | :layer_2 | :layer_3,
  :type =>
    :bridge_error
    | :connection_failed
    | :program_not_found
    | :timeout
    | :unexpected
    | :unknown
    | :validation_failed
}

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:327:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.SessionPoolV2.handle_decode_error/2

Type specification:
@spec handle_decode_error(term(), map()) :: map()

Success typing:
@spec handle_decode_error(:binary_data | :decode_error | :malformed_response, %{
  :adapter => DSPex.PythonBridge.SessionPoolV2,
  :args => _,
  :command => _,
  :from => _,
  :operation => :execute_anonymous | :execute_command,
  :worker_id => _,
  :worker_state => atom(),
  :session_id => _
}) :: %DSPex.PythonBridge.PoolErrorHandler{
  :context => map(),
  :error_category =>
    :communication_error
    | :connection_error
    | :health_check_error
    | :initialization_error
    | :python_error
    | :resource_error
    | :session_error
    | :system_error
    | :timeout_error,
  :message => binary(),
  :pool_error => true,
  :recoverable => boolean(),
  :recovery_strategy =>
    :abandon | :backoff_retry | :circuit_break | :failover | :immediate_retry,
  :retry_after => nil | 100 | 500 | 1000 | 5000 | 10000,
  :severity => :critical | :major | :minor | :warning,
  :test_layer => :layer_1 | :layer_2 | :layer_3,
  :type =>
    :bridge_error
    | :connection_failed
    | :program_not_found
    | :timeout
    | :unexpected
    | :unknown
    | :validation_failed
}

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:260:13:pattern_match_cov
The pattern
:variable_

can never match, because previous clauses completely cover the type

  {:error, :binary_data | :decode_error | :malformed_response}
  | {:error, non_neg_integer(), binary()}
  | {:ok, non_neg_integer(), _}
.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:422:5:unmatched_return
The expression produces a value of type:

atom() | :ets.tid()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:439:5:unmatched_return
The expression produces a value of type:

atom() | :ets.tid()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:461:5:unmatched_return
The expression produces a value of type:

atom() | :ets.tid()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:470:5:unmatched_return
The expression produces a value of type:

atom() | :ets.tid()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:512:5:unmatched_return
The expression produces a value of type:

atom() | :ets.tid()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:637:5:unmatched_return
The expression produces a value of type:

atom() | :ets.tid()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:683:13:unmatched_return
The expression produces a value of type:

false | non_neg_integer()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/session_pool_v2.ex:684:13:unmatched_return
The expression produces a value of type:

false | non_neg_integer()

but this value is unmatched.

________________________________________________________________________________
lib/dspex/python_bridge/worker_metrics.ex:1:pattern_match
The pattern can never match the type.

Pattern:
false

Type:
true

________________________________________________________________________________
lib/dspex/python_bridge/worker_metrics.ex:305:pattern_match
The pattern can never match the type.

Pattern:
false

Type:
true

________________________________________________________________________________
lib/dspex/python_bridge/worker_metrics.ex:348:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.WorkerMetrics.get_summary/0

Type specification:
@spec get_summary() :: map()

Success typing:
@spec get_summary() :: %{
  :events_recorded => <<_::344>>,
  :telemetry_available => true,
  :timestamp => integer()
}

________________________________________________________________________________
lib/dspex/python_bridge/worker_metrics.ex:366:pattern_match
The pattern can never match the type.

Pattern:
false

Type:
true

________________________________________________________________________________
lib/dspex/python_bridge/worker_recovery.ex:160:extra_range
The type specification has too many types for the function.

Function:
DSPex.PythonBridge.WorkerRecovery.execute_recovery/3

Extra type:
{:ok, map()}

Success typing:

  {:retry, _}
  | {:ok,
     %{
       :state_machine => %DSPex.PythonBridge.WorkerStateMachine{
         :entered_state_at => integer(),
         :health => :healthy | :unhealthy | :unknown,
         :metadata => map(),
         :state => :busy | :degraded | :initializing | :ready | :terminated | :terminating,
         :transition_history => [any()],
         :worker_id => binary()
       },
       _ => _
     }, _}
  | {:remove,
     {:recovery_removal, _}
     | {:replaced, _}
     | {:state_transition_failed,
        {:invalid_transition,
         :busy | :degraded | :initializing | :ready | :terminated | :terminating,
         :busy | :degraded | :initializing | :ready | :terminated | :terminating}}, _}


________________________________________________________________________________
lib/dspex/python_bridge/worker_recovery.ex:160:missing_range
The type specification is missing types returned by function.

Function:
DSPex.PythonBridge.WorkerRecovery.execute_recovery/3

Type specification return types:
{:ok, map()} | {:retry, non_neg_integer()} | {:remove, _, _}

Missing from spec:

  {:ok,
   %{
     :state_machine => %DSPex.PythonBridge.WorkerStateMachine{
       :entered_state_at => integer(),
       :health => :healthy | :unhealthy | :unknown,
       :metadata => map(),
       :state => :busy | :degraded | :initializing | :ready | :terminated | :terminating,
       :transition_history => [any()],
       :worker_id => binary()
     },
     _ => _
   }, _}


________________________________________________________________________________
lib/dspex/python_bridge/worker_recovery.ex:220:contract_supertype
Type specification is a supertype of the success typing.

Function:
DSPex.PythonBridge.WorkerRecovery.get_failure_delay/1

Type specification:
@spec get_failure_delay(term()) :: non_neg_integer()

Success typing:
@spec get_failure_delay(_) :: 1000 | 3000 | 5000 | 10000

________________________________________________________________________________
done (warnings were emitted)
Halting VM with exit status 2
home@U2401:~/p/g/n/dspex$
